version: '3.4'

services:
  netcorewebapp.identity.microservice:
    image: ${DOCKER_REGISTRY-}netcorewebappidentitymicroservice
    build:
      context: .
      dockerfile: NetCoreWebApp/NetCoreWebApp.Identity.Microservice/Dockerfile

  netcorewebapp.product.microservice:
    image: ${DOCKER_REGISTRY-}netcorewebappproductmicroservice
    build:
      context: .
      dockerfile: NetCoreWebApp.Product.Microservice/Dockerfile

  netcorewebapp.category.microservice:
    image: ${DOCKER_REGISTRY-}netcorewebappcategorymicroservice
    build:
      context: .
      dockerfile: NetCoreWebApp.Category.Microservice/Dockerfile

